<div class="squre_container">
            <div class="homepage" id="show_homepage">
                
            </div>
            <div class="list_user" id="show_list">
                <div class="table_user">
                    <div class="tbl_head">ID</div>
                    <div class="tbl_head">NOMBRE</div>
                    <div class="tbl_head">TIEMPO RESTANTE</div>
                    <div class="tbl_head">PROVEEDORES</div>
                    <div class="tbl_head">ESTADO</div>

                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>

                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                    <div class="IdUser">asdasgdas</div>
                    <div class="NameUser">asdasgdas</div>
                    <div class="TimeUser">asdasgdas</div>
                    <div class="ProveedorUser">asdasgdas</div>
                    <div class="ConditionUser">asdasgdas</div>
                </div>
            </div>
            <div class="add_user"></div>
            <div class="delete_user"></div>
            <div class="update_user"></div>
            <div class="recordar_sus"></div>
            <div class="see_proveedores"></div>
        </div>